### ISSUE TITLE
utility passbook

### ISSUE THREAD

**Issue by jmbarcial** [sdcc-i-coop-portal/zoom114#1]
- cover pages

**Comment by regiboy** [comment]
* Paano malalaman kung debit or credit yung audit_total?

**Comment by regiboy** [comment]
- dapat sunod-sunod yan, bawal bungi
- pag nag-balance forwarded na yung dulo (end ng prev passbook), dapat ma-print yung continuation niya from the very first line
- dapat may line number range ito; and starting line ng i-prprint.

**Comment by regiboy** [comment]
* Implemented print range and print line start.
* sablay na pala yung computation ng balance forwarded; reason is paano malalaman kung debit or credit yung audit_total?

**Comment by regiboy** [comment]
* Added 'Print aflatoun first page' option if SD, and is AF
* to fix pa yung withdraw/deposit

**Comment by regiboy** [comment]
* DPCK

**Comment by regiboy** [comment]
Cover page done since 2017-10-03

**Comment by regiboy** [comment]
* Computation of account balance with multiple details (esp. DPCK)
    * done since 2017-10-04
